name: cl_server_examples
description: CLI utilities for managing users and store entities in CL Server using the Dart client library.
version: 1.0.0

publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  args: ^2.4.0
  cl_server_dart_client:
    path: ../
  path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
